security:
    enable_authenticator_manager: true
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            access_denied_handler: App\Security\AccessDeniedHandler
#            anonymous: true
            lazy: true
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: security_logout
            login_link:
                check_route: login_check
                signature_properties: ['id']
                lifetime: 600
                max_uses: 1
    access_control:
#        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
#         - { path: ^/profile, roles: ROLE_USER }
#        - { path: ^/admin, roles: ROLE_ADMIN }
